
# Limites do Sistema
LIMITE_TAMANHO_GRANDE = 100000
TAXA_QUASE_ORDENADO = 0.10  # 10% de inversões

# Sistema de Pontuação do Motor de Decisão
PONTUACAO_BASE = 100
BONUS_QUASE_ORDENADO = 35
PENALIDADE_ESTABILIDADE = 50
PENALIDADE_MEMORIA = 30