# Sistema de Pontuação (Motor de Decisão)
PONTUACAO_BANIDO = -1000
PONTUACAO_CORTE_ALTERNATIVA = -500

# Limites / Thresholds do Sistema
LIMITE_TAMANHO_BUSCA_PEQUENA = 30
LIMITE_TAMANHO_ORDENACAO_MEDIO = 100
LIMITE_TAMANHO_QUASE_ORDENADO = 2000

GRAU_QUASE_ORDENADO_IDEAL = 0.10
GRAU_QUASE_ORDENADO_LIMITE_INSERTION = 0.12
GRAU_INVERSAO_ALTO_QUICK = 0.70
GRAU_ALTAMENTE_INVERTIDO = 0.85

# Pontuações Iniciais - Busca
SCORE_BASE_BUSCA_SEQUENCIAL = 50
SCORE_BASE_BUSCA_BINARIA = 40
SCORE_BASE_BUSCA_HASH = 60

# Pontuações Iniciais - Ordenação
SCORE_BASE_INSERTION = 30
SCORE_BASE_SELECTION = 25
SCORE_BASE_BUBBLE = 20
SCORE_BASE_MERGE = 50
SCORE_BASE_QUICK = 55
SCORE_BASE_HEAP = 45